### ISSUE TITLE
license GPL for this repo?

### ISSUE THREAD

**Issue by PhilLAL** [tango-controls/TangoDatabase#14]
Hi there, 
reading the repositories of tango-controls, I've noticed there no license is specified here.
What is the license applied to this soft? Is it GPL?

**Comment by bourtemb** [comment]
As you can see in the headers of the files, the license is GPL.
It's indeed a good idea to add a License file for this repository.

**Comment by bourtemb** [comment]
GPL v3 License added in fd1fb056d44490028edf7a1d4df35c4d3b88afbf

Thanks @PhilLAL for creating this issue.
We need to update the README file too because it is obsolete (Last update was 8 years ago).
