### ISSUE TITLE
Cannot build on gentoo

### ISSUE THREAD

**Issue by dlacoste-esrf** [tango-controls/TangoDatabase#23]
Trying to build on gentoo, compilation is failing against mariadb or mysql.

`/var/tmp/portage/ctrl-tango/tango-db-5.15/work/TangoDatabase-Database-Release-5.14/DataBaseUtils.cpp:784:3: error: ‘my_bool’ was not declared in this scope; did you mean ‘bool’?
  784 |   my_bool my_auto_reconnect=1;`
`/var/tmp/portage/ctrl-tango/tango-db-5.15/work/TangoDatabase-Database-Release-5.14/DataBaseUtils.cpp:785:61: error: ‘my_auto_reconnect’ was not declared in this scope
  785 |   if (mysql_options(conn_pool[loop].db,MYSQL_OPT_RECONNECT,&my_auto_reconnect) !=0)`

mysql version 8.0.20
mariadb version 10.4.12

Upon checking this my_bool is defined in mysql.h but it is not defined for mysql.
As for mariadb this file can be found in 2 places : 
  - /usr/include/mysql/
  - /usr/include/mariadb/

But on configure/FindMysql.cmake, we only check on the first directory, and cannot build. Changing the path there fix the issue.

Mariadb installation on gentoo might not use default path, so we might not have this issue on other distributions with mariadb. But if my_bool is not defined in newer version of mysql, we might need to change the code not to use it anymore.

**Comment by mliszcz** [comment]
Relevant changelog entry: https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html
> Incompatible Change: The my_bool type is no longer used in MySQL source code. Any third-party code that used this type to represent C boolean variables should use the bool or int C type instead.
