### ISSUE TITLE
DbExportServer/DbUnexportServer

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/TangoDatabase#6]
There is no longer DbExportServer command (as mentioned by @bourtemb in https://github.com/tango-controls/JTango/pull/33). Maybe DbUnexportServer must be removed as well as its counterpart?

**Comment by bourtemb** [comment]
According to the documentation: 
DbUnExportServer method is doing the following:

> "Mark all devices belonging to a specified device server process as non exported"

This will update the _device_ table for all the devices belonging to a server and set the exported column to 0 and the stopped column to NOW().
DbUnExportServer is still used, typically when a device server is stopped.
This command must not be removed.
